#- name: prerequisites for Multimaster kubernetes cluster
#  hosts: kubernetes
#  become: true
#  roles:
#    - role: common
#      state: present

- name: Kubernetes installation
  hosts: masters
  become: true
  serial: 3
  vars:
    keepalived_virtual_ipaddress: '10.51.0.4'
  roles:
  - role: keepalived
    state: present

- name: Initialize for Multimaster kubernetes cluster
  hosts: masters
  become: true
  roles:
    - role: master
      state: present

- name: Add Worker node on  kubernetes cluster
  hosts: workers
  become: true
  roles:
    - role: worker
      state: present
