---
- name: Install keepalived and Update repositories
  ansible.builtin.apt:
    name: keepalived
    update_cache: true

- include_tasks: master.yaml
  when: inventory_hostname == 'master1'

- include_tasks: backup.yaml
  when: inventory_hostname != 'master1'

- name: enable keepalived at startup
  ansible.builtin.service:
    name: keepalived
    enabled: yes
    state: started

