- name: Copy join command from Ansiblehost to the worker nodes.
  copy:
    src: /tmp/worker_join_command
    dest: /tmp/worker_join_command
    mode: 0777

- name: Join the Worker nodes to the cluster.
  command: sh /tmp/worker_join_command
  register: joined_or_not
