- name: Update apt repository
  apt:
    update_cache: yes

- name: Install containerd
  apt:
    name: containerd
    state: present

- name: Enable and start containerd service
  systemd:
    name: containerd
    enabled: yes
    state: started

- name: Install required dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings/
    state: directory
    mode: '0755'

- name: Add Kubernetes apt repository key
  shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes apt repository
  shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list

- name: Update apt repository after adding Kubernetes repo
  apt:
    update_cache: yes

- name: Install Kubernetes components
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Disable swap
  command: swapoff -a

- name: Ensure net.ipv4.ip_forward is set to 1 in sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net.ipv4.ip_forward'
    line: 'net.ipv4.ip_forward=1'
    state: present

- name: Apply sysctl settings
  command: sysctl -p
