- name: Initialize first master node
  include_tasks: init.yaml
  when: inventory_hostname == 'master1'
  register: master1_init_result
  run_once: true

- name: Check if master1 init failed
  fail:
    msg: "Master1 initialization failed. Exiting playbook."
  when: master1_init_result is failed

- name: Set fact after master1 init
  set_fact:
    master1_initialized: true
  when: inventory_hostname == 'master1'

- name: Wait for master1 to complete initialization
  wait_for:
    path: /etc/kubernetes/admin.conf
    state: present
    timeout: 300
  delegate_to: master1
  run_once: true

- name: Configure multi-master nodes
  include_tasks: multimaster.yaml
  when: inventory_hostname != 'master1' and hostvars['master1']['master1_initialized'] | default(false)

- name: Copy Keepalived.conf for MASTER Nodes
  template:
    src: check_apiserver.sh.j2
    dest: /etc/keepalived/check_apiserver.sh
    mode: +x

- name: restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
