- name: Initialize first master node
  include_tasks: init.yaml
  when: inventory_hostname == 'master1'
  register: master1_init_result
  run_once: true

- name: Set fact after master1 init
  set_fact:
    master1_initialized: true
  when: inventory_hostname == 'master1'

- name: Wait for master1 to complete initialization
  wait_for:
    path: /etc/kubernetes/admin.conf
    state: present
    timeout: 300
  delegate_to: master1
  run_once: true

- name: Configure multi-master nodes
  include_tasks: multimaster.yaml
  when: inventory_hostname != 'master1' and hostvars['master1']['master1_initialized'] | default(false)

