---
- name: Copy kubernetes certs and admin.conf
  copy:
    src: /tmp/kubernetes
    dest: /etc/

- name: Copy join command from Ansiblehost to the master nodes.
  copy:
    src: /tmp/kubernetes_join_command
    dest: /tmp/kubernetes_join_command
    mode: 0777

- name: Join the Another Master nodes to the cluster.
  command: sh /tmp/kubernetes_join_command
  register: joined_or_not


